DROP TABLE IF EXISTS run_events;
DROP TABLE IF EXISTS publish_items;
DROP TABLE IF EXISTS publish_records;
DROP TABLE IF EXISTS article_ai_results;
DROP TABLE IF EXISTS feed_entries;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS feed_sources;
DROP TABLE IF EXISTS raw_artifacts;
DROP TABLE IF EXISTS rule_versions;
