-- PostgreSQL 翻译版（W11-P3-A）。与 migrations/sqlite/0001_init.up.sql 严格对齐：
-- 表列顺序、UNIQUE 列组、CHECK 谓词、索引列组、FK 行为均保持一致。
--
-- 翻译规则（对齐 docs-backup/design/storage-multi-dialect.md §4.2 + §7）：
--   INTEGER PRIMARY KEY            → BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   INTEGER（domain i64：count/version/priority/lease/byte_size 等）→ BIGINT
--   INTEGER NULL（domain Option<i32>：importance_score / frozen_score / keep_decision）→ INTEGER
--   TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP → TIMESTAMPTZ NOT NULL DEFAULT NOW()
--   TEXT NULL（lease_expires_at / *_at 时间字段）→ TIMESTAMPTZ NULL
--   TEXT NOT NULL（discovered_at 无默认时间）→ TIMESTAMPTZ NOT NULL
--   TEXT NOT NULL（report_date / *_key / *_json 等域内字符串）→ TEXT NOT NULL（domain 字段就是 String）
--   BLOB NULL → BYTEA NULL
--
-- 建表顺序按拓扑序排：SQLite 容忍 forward-reference FK，PG 不行。
-- articles 表与 feed_entries 互相 FK 引用，先建无 origin_feed_entry_id FK
-- 的 articles，再建 feed_entries，最后 ALTER TABLE articles 补 FK。

CREATE TABLE rule_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    version_tag TEXT NOT NULL,
    description TEXT NOT NULL,
    payload_sha256 TEXT NOT NULL,
    retired_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (kind, version_tag)
);

CREATE INDEX idx_rule_versions_kind_retired_at
    ON rule_versions (kind, retired_at);

CREATE TABLE raw_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    artifact_key TEXT NOT NULL,
    content_encoding TEXT NOT NULL,
    storage_kind TEXT NOT NULL,
    inline_body BYTEA NULL,
    file_path TEXT NULL,
    byte_size BIGINT NOT NULL,
    sha256 TEXT NOT NULL,
    retention_policy TEXT NOT NULL,
    expires_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (kind, artifact_key),
    CHECK ((storage_kind='inline' AND inline_body IS NOT NULL) OR (storage_kind='file' AND file_path IS NOT NULL))
);

CREATE INDEX idx_raw_artifacts_expires_at
    ON raw_artifacts (expires_at);

CREATE INDEX idx_raw_artifacts_kind
    ON raw_artifacts (kind);

CREATE TABLE feed_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_key TEXT NOT NULL,
    source_key TEXT NOT NULL,
    display_name TEXT NOT NULL,
    feed_url TEXT NOT NULL,
    feed_kind TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    priority BIGINT NOT NULL DEFAULT 100,
    etag TEXT NULL,
    last_modified TEXT NULL,
    last_fetched_at TIMESTAMPTZ NULL,
    last_success_at TIMESTAMPTZ NULL,
    consecutive_failures BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    last_error_kind TEXT NULL,
    config_version BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (category_key, source_key),
    FOREIGN KEY (config_version) REFERENCES rule_versions(id)
);

CREATE INDEX idx_feed_sources_status
    ON feed_sources (status);

CREATE INDEX idx_feed_sources_category_priority
    ON feed_sources (category_key, priority);

-- articles 先不带 origin_feed_entry_id FK（feed_entries 尚未存在），下文 ALTER 后补。
CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_hash TEXT NOT NULL,
    canonical_link TEXT NOT NULL,
    title TEXT NOT NULL,
    body_text TEXT NOT NULL,
    body_html_artifact_id BIGINT NULL,
    extractor_strategy TEXT NOT NULL,
    extractor_version BIGINT NOT NULL,
    content_quality TEXT NOT NULL,
    word_count BIGINT NOT NULL DEFAULT 0,
    origin_feed_entry_id BIGINT NOT NULL,
    state TEXT NOT NULL DEFAULT 'persisted',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (content_hash),
    FOREIGN KEY (extractor_version) REFERENCES rule_versions(id),
    FOREIGN KEY (body_html_artifact_id) REFERENCES raw_artifacts(id) ON DELETE SET NULL
);

CREATE INDEX idx_articles_canonical_link
    ON articles (canonical_link);

CREATE INDEX idx_articles_state_created_at
    ON articles (state, created_at);

CREATE TABLE feed_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    feed_entry_uid TEXT NOT NULL,
    normalized_link TEXT NOT NULL,
    link_hash TEXT NOT NULL,
    title_raw TEXT NOT NULL,
    summary_raw TEXT NULL,
    published_at TIMESTAMPTZ NULL,
    discovered_at TIMESTAMPTZ NOT NULL,
    state TEXT NOT NULL DEFAULT 'discovered',
    dedup_decision TEXT NULL,
    article_id BIGINT NULL,
    lease_owner TEXT NULL,
    lease_expires_at TIMESTAMPTZ NULL,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    last_error_kind TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (source_id, feed_entry_uid),
    FOREIGN KEY (source_id) REFERENCES feed_sources(id),
    FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE SET NULL
);

-- 补回 articles → feed_entries 的循环 FK（SQLite 编译期不解析，PG 必须延后）。
ALTER TABLE articles
    ADD CONSTRAINT articles_origin_feed_entry_id_fkey
    FOREIGN KEY (origin_feed_entry_id) REFERENCES feed_entries(id);

CREATE INDEX idx_feed_entries_link_hash
    ON feed_entries (link_hash);

CREATE INDEX idx_feed_entries_state_lease_expires_at
    ON feed_entries (state, lease_expires_at);

CREATE INDEX idx_feed_entries_source_discovered_at
    ON feed_entries (source_id, discovered_at);

CREATE TABLE article_ai_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    prompt_version BIGINT NOT NULL,
    output_schema_version BIGINT NOT NULL,
    model_id TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'pending',
    summary TEXT NULL,
    tags_json TEXT NULL,
    importance_score INTEGER NULL,
    keep_decision INTEGER NULL,
    raw_response_artifact_id BIGINT NULL,
    tokens_in BIGINT NULL,
    tokens_out BIGINT NULL,
    cost_micro_usd BIGINT NULL,
    latency_ms BIGINT NULL,
    lease_owner TEXT NULL,
    lease_expires_at TIMESTAMPTZ NULL,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    last_error_kind TEXT NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (article_id, prompt_version, output_schema_version, model_id),
    FOREIGN KEY (article_id) REFERENCES articles(id),
    FOREIGN KEY (prompt_version) REFERENCES rule_versions(id),
    FOREIGN KEY (output_schema_version) REFERENCES rule_versions(id),
    FOREIGN KEY (raw_response_artifact_id) REFERENCES raw_artifacts(id) ON DELETE SET NULL,
    CHECK (importance_score IS NULL OR (importance_score BETWEEN 0 AND 100)),
    CHECK (keep_decision IS NULL OR keep_decision IN (0, 1))
);

CREATE INDEX idx_article_ai_results_state_lease_expires_at
    ON article_ai_results (state, lease_expires_at);

CREATE INDEX idx_article_ai_results_article_id
    ON article_ai_results (article_id);

CREATE TABLE publish_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key TEXT NOT NULL,
    category_key TEXT NOT NULL,
    report_date TEXT NOT NULL,
    target_timezone TEXT NOT NULL,
    render_version BIGINT NOT NULL,
    selection_policy_version BIGINT NOT NULL,
    state TEXT NOT NULL DEFAULT 'pending',
    snapshot_frozen_at TIMESTAMPTZ NULL,
    rendered_at TIMESTAMPTZ NULL,
    local_stored_at TIMESTAMPTZ NULL,
    remote_published_at TIMESTAMPTZ NULL,
    local_path TEXT NULL,
    remote_target TEXT NULL,
    commit_sha TEXT NULL,
    lease_owner TEXT NULL,
    lease_expires_at TIMESTAMPTZ NULL,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    last_error_kind TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (idempotency_key),
    FOREIGN KEY (render_version) REFERENCES rule_versions(id),
    FOREIGN KEY (selection_policy_version) REFERENCES rule_versions(id)
);

CREATE INDEX idx_publish_records_category_report_date
    ON publish_records (category_key, report_date);

CREATE INDEX idx_publish_records_state_lease_expires_at
    ON publish_records (state, lease_expires_at);

CREATE TABLE publish_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publish_record_id BIGINT NOT NULL,
    position BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    article_ai_result_id BIGINT NULL,
    frozen_title TEXT NOT NULL,
    frozen_summary TEXT NOT NULL,
    frozen_tags_json TEXT NOT NULL,
    frozen_score INTEGER NULL,
    frozen_canonical_link TEXT NOT NULL,
    frozen_source_display_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (publish_record_id, article_id),
    FOREIGN KEY (publish_record_id) REFERENCES publish_records(id) ON DELETE CASCADE,
    FOREIGN KEY (article_id) REFERENCES articles(id),
    FOREIGN KEY (article_ai_result_id) REFERENCES article_ai_results(id),
    CHECK ((article_ai_result_id IS NOT NULL AND frozen_score IS NOT NULL) OR (article_ai_result_id IS NULL AND frozen_score IS NULL)),
    CHECK (frozen_score IS NULL OR (frozen_score BETWEEN 0 AND 100))
);

CREATE INDEX idx_publish_items_record_position
    ON publish_items (publish_record_id, position);

CREATE TABLE run_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL,
    trace_id TEXT NULL,
    stage TEXT NOT NULL,
    severity TEXT NOT NULL,
    event_kind TEXT NOT NULL,
    target_kind TEXT NULL,
    target_id BIGINT NULL,
    message TEXT NOT NULL,
    context_json TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_run_events_run_id
    ON run_events (run_id);

CREATE INDEX idx_run_events_stage_severity_created_at
    ON run_events (stage, severity, created_at);

CREATE INDEX idx_run_events_target_kind_target_id
    ON run_events (target_kind, target_id);
