-- F15-1 W9-F3+W9-F4 的 PG 翻译，与 migrations/sqlite/0002 严格对齐。
--
-- 1. rule_versions.status 列 + partial unique index (kind WHERE status='active')
-- 2. reindex_jobs 表 + 复合索引 + 约束
--
-- backfill 策略与 SQLite 版相同（详见 sqlite/0002 上半部分注释）：
--   step 1: retired_at IS NOT NULL 的行直接映射为 superseded
--   step 2: 同 kind 未退役多行时，仅 max(id) 保留 active，其余 superseded
--
-- 一次性 backfill；之后由 reindex flow + active_rule_or_register 维护。

ALTER TABLE rule_versions
    ADD COLUMN status TEXT NOT NULL DEFAULT 'active';

UPDATE rule_versions
   SET status = 'superseded'
 WHERE retired_at IS NOT NULL;

UPDATE rule_versions
   SET status = 'superseded'
 WHERE retired_at IS NULL
   AND id NOT IN (
       SELECT MAX(id)
         FROM rule_versions
        WHERE retired_at IS NULL
        GROUP BY kind
   );

-- partial unique index: 同 kind 至多一行 status='active'
CREATE UNIQUE INDEX uq_rule_versions_kind_active
    ON rule_versions (kind)
    WHERE status = 'active';

CREATE INDEX idx_rule_versions_kind_status
    ON rule_versions (kind, status);

CREATE TABLE reindex_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target TEXT NOT NULL,
    rule_version_id BIGINT NOT NULL,
    last_processed_id BIGINT NULL,
    total_estimated BIGINT NULL,
    state TEXT NOT NULL,
    error TEXT NULL,
    aborted_reason TEXT NULL,
    lease_owner TEXT NULL,
    lease_expires_at TIMESTAMPTZ NULL,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NULL,
    finished_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (rule_version_id) REFERENCES rule_versions(id),
    CHECK (state != 'completed' OR finished_at IS NOT NULL),
    CHECK (state != 'aborted' OR aborted_reason IS NOT NULL)
);

-- partial unique index: 同 target 至多一个未完成 job
CREATE UNIQUE INDEX uq_reindex_jobs_target_active
    ON reindex_jobs (target)
    WHERE state IN ('pending', 'running');

-- reclaim 扫描索引（state + lease_expires_at）
CREATE INDEX idx_reindex_jobs_state_lease
    ON reindex_jobs (state, lease_expires_at);
