[package]
name = "rss-ai-news-publish"
version.workspace = true
edition.workspace = true

[dependencies]
rss-ai-news-domain.workspace = true
async-trait = "0.1"
octocrab.workspace = true
time.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
